.build-and-push:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
  - docker push "$IMAGE_NAME:$IMAGE_TAG"
