.test:
  - apt-get update && apt-get install -y unzip git libzip-dev libxml2-dev
  - docker-php-ext-install zip pdo pdo_mysql xml
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --no-interaction --prefer-dist
  - vendor/bin/phpunit
